### ISSUE TITLE
Technical setting names easily confused

### ISSUE THREAD

**Issue by Awkanimus** [QuoteNat/vein_miner#12]
Settings don't have namespaces and when you are configuring a server, the names `allow_ores`, `allow_trees`, and `allow_all` don't pop out as belonging to vein_miner. In addition, `allow_all` could easily be used by another mod.

I recommend prefixing the names which is common in other mods to `vein_miner_allow_ores`, `vein_miner_allow_trees`, and `vein_miner_allow_all`.
 
For backwards compatibility, we can make the settings prefer the new names, but accept the old if the new ones are omitted and the old ones are present.

I'm happy to submit a PR if desired.

**Comment by QuoteNat** [comment]
Should be resolved by #16.
